### ISSUE TITLE
Another breaking change

### ISSUE THREAD

**Issue by naanlizard** [jaredwray/keyv#1378]
> [deps 3/3] RUN yarn build:
0.399 yarn run v1.22.22
0.434 $ tsc
8.090 src/entityRepository.ts(62,7): error TS2322: Type 'Keyv<any>' is not assignable to type 'KeyvStoreAdapter | Keyv<any>'.
8.090   Type 'import("/usr/app/node_modules/keyv/dist/index").Keyv<any>' is not assignable to type 'import("/usr/app/node_modules/@keyv/redis/node_modules/keyv/dist/index").Keyv<any>'.
8.090     Types have separate declarations of a private property '_ttl'.
8.090 src/program/index.ts(152,7): error TS2322: Type 'Keyv<any>' is not assignable to type 'KeyvStoreAdapter | Keyv<any>'.
8.090   Type 'import("/usr/app/node_modules/keyv/dist/index").Keyv<any>' is not assignable to type 'import("/usr/app/node_modules/@keyv/redis/node_modules/keyv/dist/index").Keyv<any>'.
8.090     Types have separate declarations of a private property '_ttl'.

**Comment by naanlizard** [comment]
Works perfectly fine in 5.3.2, 5.3.3 breaks

**Comment by jaredwray** [comment]
This is because Keyv needs to be a peerDependency so we can release it at different types. New `@keyv/redis` will be published shortly.

**Comment by jaredwray** [comment]
@naanlizard - this is fixed now on `@keyv/redis` and published as `v4.3.4`

**Comment by jaredwray** [comment]
Here is all the fixes: https://github.com/jaredwray/keyv/releases/tag/2025-04-20

**Comment by rklos** [comment]
I'm still experiencing the same problem even after upgrading to the latest version:
```json
"@keyv/redis": "4.3.4",
"keyv": "5.3.3",
```

```bash
TS2322: Type 'Keyv<any>[]' is not assignable to type 'Keyv<any> | KeyvStoreAdapter | (Keyv<any> | KeyvStoreAdapter)[]'.
  Type 'Keyv<any>[]' is not assignable to type '(Keyv<any> | KeyvStoreAdapter)[]'.
    Type 'Keyv<any>' is not assignable to type 'Keyv<any> | KeyvStoreAdapter'.
      Type 'import("/project/node_modules/keyv/dist/index").Keyv<any>' is not assignable to type 'import("/project/node_modules/keyv/dist/index").Keyv<any>'. Two different types with this name exist, but they are unrelated.
        Types have separate declarations of a private property '_ttl'.
```

**Comment by jaredwray** [comment]
Is this a project I can look at because it should be fixed. Can you also delete `node_modules`?

**Comment by rklos** [comment]
Ok, I've done some debugging and research and the cause of the problem was `@nestjs/swagger/plugin` transformer in my project's webpack configuration.

**Comment by jaredwray** [comment]
@rklos - did you figure out a fix for it?

**Comment by rklos** [comment]
@jaredwray I've created an issue in @nestjs/swagger's repo: https://github.com/nestjs/swagger/issues/3420
